--SYS

--DBA로 시작하는 DICTIONARY는 관리자모드에서만 볼수있다.
SELECT * FROM DBA_UNUSED_COL_TABS; --DICTIONARY --비활성화 시킨 테이블 정보를 보여줌

--DCL(GRANT,REVOKE)
--GRANT : USER나 OBJECT에 권한을 부여할 때 사용
--REVOKE : 권한을 회수할 때 사용

CREATE USER TEST
IDENTIFIED BY TEST
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 1M ON USERS;

CREATE USER INSA
IDENTIFIED BY INSA
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 1M ON USERS;


SELECT * FROM DBA_USERS;

--현재 DB에 접속한 사람들의 리스트 확인
SELECT * FROM V$SESSION
WHERE USERNAME IS NOT NULL;

--권한의 종류 
--CREATE TABLE 권한을 받게되면 ALTER,DROP TABLE도 자동으로 부여됨
--CREATE ANY TABLE : 다른 사용자의 테이블도 만들어줄 수 있음 

--SYSTEM 권한 : DATABACE의 OBJECT들을 CREATE(생성),ALTER(수정),DROP(삭제) 할 수 있는 권한
--              DBA -> USERS
--OBJECT 권한 : USER가 만든 OBJECT를 조작(INSERT,UPDATE,DELETE,SELECT)
--OBJECT : TABLE,ROLE,SEQUENCE,VIEW,SYNONIM
--------------------------------------------------
SELECT * FROM SYSTEM_PRIVILEGE_MAP;

GRANT CREATE USER TO KIM; --PUBLIC : 모든사람
GRANT CREATE SESSION TO TEST;

SELECT * FROM ALL_USERS;

--OBJECT 권한
--다른 사용자에게 나의 테이블에대한 권한을 줌
--TEST가 KIM테이블의 권한을 부여받고 사용하려면 FROM에 KIM.테이블명으로 표시해야함
--그때 계정명 KIM을 스키마라고 함 

GRANT CREATE SESSION, CREATE SYNONYM TO TEST;

--테이블에 별칭을 줘서 사용할 수 있게하는 명령어
--CREATE SYNONYM KIMDIV FOR KIM.DIVISION;
--SELECT * FROM KIMDIV; 로 사용 가능 
------------------------------------------------------------------------------------------------
--ROLE(역할)
--CONNECT,RESOURCE

SELECT * FROM ROLE_SYS_PRIVS WHERE ROLE IN('CONNECT','RESOURCE','MANAGER');

CREATE ROLE MANAGER;

SELECT * FROM DBA_ROLES;

GRANT CREATE SESSION,CREATE TABLE,CREATE USER TO MANAGER;

GRANT MANAGER TO INSA;
REVOKE MANAGER FROM INSA;

GRANT CREATE VIEW TO kim;